import {getD1} from "../../../../db";
import {ebayConfig} from "../../../../lib/ebay";
import {putImage,requireOwner,stableJson} from "../../../../lib/studio-persistence";
export const runtime="edge";

function decodeDataUrl(value:string){const match=value.match(/^data:([^;]+);base64,(.+)$/);if(!match)throw new Error("A photograph was not supplied as a supported image.");const bytes=Uint8Array.from(atob(match[2]),character=>character.charCodeAt(0));return{contentType:match[1],data:bytes.buffer}}

export async function GET(request:Request){try{const owner=requireOwner(request),url=new URL(request.url),id=url.searchParams.get("id"),db=getD1();if(id){const item=await db.prepare("SELECT * FROM studio_items WHERE id=? AND owner_email=?").bind(id,owner).first<any>();if(!item)return Response.json({error:"Item not found."},{status:404});const photos=await db.prepare("SELECT id,object_key,sha256,content_type,file_name,ordinal FROM studio_photos WHERE item_id=? ORDER BY ordinal").bind(id).all<any>();return Response.json({item:{...item,payload:JSON.parse(item.payload_json)},photos:photos.results??[]})}const rows=await db.prepare("SELECT * FROM studio_items WHERE owner_email=? ORDER BY updated_at DESC").bind(owner).all<any>();return Response.json({items:(rows.results??[]).map((item:any)=>({...item,payload:JSON.parse(item.payload_json)}))})}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to load durable items."},{status:400})}}

export async function PUT(request:Request){try{const owner=requireOwner(request),body:any=await request.json(),config=ebayConfig(),id=String(body.id||"").trim(),sku=String(body.sku||"").trim();if(!id||!sku)return Response.json({error:"Item ID and deterministic SKU are required."},{status:400});if(body.environment&&body.environment!==config.environment)return Response.json({error:"Item environment does not match the connected eBay environment."},{status:409});const now=Date.now(),dimensions=body.dimensions??{},payload={facts:body.facts??{},evidence:body.evidence??[],copy:body.copy??{},approval:body.approval??null,intendedOffer:body.intendedOffer??{},batchId:body.batchId??null};await getD1().prepare("INSERT INTO studio_items (id,owner_email,sku,marketplace_id,listing_format,environment,content_status,evidence_status,sync_status,offer_status,publication_status,operation_status,payload_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET sku=excluded.sku,marketplace_id=excluded.marketplace_id,listing_format=excluded.listing_format,environment=excluded.environment,content_status=excluded.content_status,evidence_status=excluded.evidence_status,sync_status=excluded.sync_status,offer_status=excluded.offer_status,publication_status=excluded.publication_status,operation_status=excluded.operation_status,payload_json=excluded.payload_json,updated_at=excluded.updated_at").bind(id,owner,sku,config.marketplaceId,String(body.listingFormat||"FIXED_PRICE"),config.environment,String(dimensions.content||"incomplete"),String(dimensions.evidence||"uncertain"),String(dimensions.sync||"absent"),String(dimensions.offer||"absent"),String(dimensions.publication||"unpublished"),String(dimensions.operation||"idle"),stableJson(payload),now,now).run();const photos=[];for(const [ordinal,photo] of (Array.isArray(body.photos)?body.photos:[]).entries()){const decoded=decodeDataUrl(String(photo.data||""));photos.push(await putImage(owner,id,{id:String(photo.id||crypto.randomUUID()),fileName:String(photo.fileName||`photo-${ordinal+1}.jpg`),contentType:decoded.contentType,ordinal,data:decoded.data}))}return Response.json({saved:true,id,sku,environment:config.environment,durablePhotoCount:photos.length,updatedAt:now})}catch(error){return Response.json({error:error instanceof Error?error.message:"Unable to save the durable item."},{status:400})}}
