import test from "node:test";
import assert from "node:assert/strict";
import {buildManifest,classifyRemote,compareManifest,hash,recoverUnknown,stableJson,validatePrepared} from "../lib/rescue-core.mjs";
const item={itemId:"i1",sku:"LW-1",title:"Manual",description:"Body",categoryId:"934",leafCategory:true,condition:"USED_GOOD",photos:[{id:"p2",sha256:"b",ordinal:2},{id:"p1",sha256:"a",ordinal:1}],price:19.99,priceApproved:true,quantity:1,bestOfferEnabled:true,packageDetails:{weight:{value:1,unit:"POUND"},dimensions:{length:10,width:8,height:1,unit:"INCH"}},policies:{paymentPolicyId:"p",fulfillmentPolicyId:"f",returnPolicyId:"r"},merchantLocationKey:"L1",aspects:{Brand:["RCA"]}};
test("stable manifests retain photo order and hash deterministically",()=>{const a=buildManifest(item),b=buildManifest({...item,aspects:{Brand:["RCA"]}});assert.equal(a.manifestHash,b.manifestHash);assert.deepEqual(a.manifest.photos.map(x=>x.id),["p1","p2"]);assert.equal(hash(a.manifest),a.manifestHash);assert.equal(stableJson({b:1,a:2}),'{"a":2,"b":1}')});
test("duplicate audit combines Inventory and seller listing inventory",()=>{assert.equal(classifyRemote({sku:"LW-1",inventoryOffers:[{sku:"LW-1",offerId:"o"}],sellerListings:[]}).classification,"RECOVERABLE");assert.equal(classifyRemote({sku:"LW-1",inventoryOffers:[{sku:"LW-1",listingId:"1"}],sellerListings:[{customLabel:"LW-1",itemId:"2",status:"ACTIVE"}]}).classification,"DUPLICATE_RISK")});
test("unknown mutations reconcile before retry",()=>{assert.equal(recoverUnknown({sku:"LW-1",offers:[],listings:[]}).action,"RETRY_ONCE");assert.equal(recoverUnknown({sku:"LW-1",offers:[{sku:"LW-1",offerId:"o"}],listings:[]}).action,"RECOVER_OFFER");assert.equal(recoverUnknown({sku:"LW-1",offers:[{sku:"LW-1",listingId:"1"}],listings:[]}).action,"RECONCILE_LIVE")});
test("prepared validation requires price, package, policies and evidence closure",()=>{assert.equal(validatePrepared(item).ready,true);const result=validatePrepared({...item,priceApproved:false,unresolvedClaims:["year"]});assert.equal(result.ready,false);assert.match(result.issues.join(" "),/approved item-specific price/);assert.match(result.issues.join(" "),/Unresolved factual claims/)});
test("reconciliation reports material fields only",()=>{const {manifest}=buildManifest(item);assert.equal(compareManifest(manifest,item).pass,true);assert.deepEqual(compareManifest(manifest,{...item,price:29.99}).diffs,["price"])});
