import {createHash} from "node:crypto";

export const STATES=["READY","NEEDS_INPUT","VERIFIED","PUBLISHING_UNKNOWN","LIVE_RECONCILED","BLOCKED","NOT_ATTEMPTED"];
export function stableJson(value){if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stableJson).join(",")}]`;return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stableJson(value[key])}`).join(",")}}`}
export function hash(value){return createHash("sha256").update(typeof value==="string"?value:stableJson(value)).digest("hex")}
export function redact(value){if(Array.isArray(value))return value.map(redact);if(!value||typeof value!=="object")return value;return Object.fromEntries(Object.entries(value).map(([key,item])=>[/secret|token|authorization|cookie/i.test(key)?[key,"[REDACTED]"]:[key,redact(item)]]))}
export function classifyRemote({sku,inventoryOffers=[],sellerListings=[]}){const offers=inventoryOffers.filter(x=>x.sku===sku),listings=sellerListings.filter(x=>x.sku===sku||x.customLabel===sku),live=[...offers.filter(x=>x.listingId),...listings.filter(x=>["ACTIVE","SCHEDULED"].includes(String(x.status).toUpperCase()))],identities=new Set(live.map(x=>String(x.listingId||x.itemId||x.id)));if(identities.size>1||offers.length>1)return{classification:"DUPLICATE_RISK",offers,listings};if(live.length)return{classification:"ALREADY_LIVE",offers,listings};if(offers.length===1)return{classification:"RECOVERABLE",offers,listings};return{classification:"CLEAR",offers,listings}}
export function buildManifest(item){const manifest={schemaVersion:1,itemId:String(item.itemId),sku:String(item.sku),environment:"production",marketplaceId:String(item.marketplaceId||"EBAY_US"),photos:(item.photos||[]).map(({id,sha256,ordinal,epsUrl})=>({id:String(id),sha256:String(sha256),ordinal:Number(ordinal),epsUrl:epsUrl?String(epsUrl):null})).sort((a,b)=>a.ordinal-b.ordinal),title:String(item.title||""),description:String(item.description||""),categoryId:String(item.categoryId||""),leafCategory:item.leafCategory===true,condition:String(item.condition||""),aspects:item.aspects||{},price:{currency:String(item.currency||"USD"),value:Number(item.price||0).toFixed(2)},quantity:Number(item.quantity||1),bestOfferEnabled:item.bestOfferEnabled!==false,packageDetails:item.packageDetails||{},policies:item.policies||{},merchantLocationKey:String(item.merchantLocationKey||"")};return{manifest,manifestHash:hash(manifest)}}
export function validatePrepared(item){const issues=[];if(!item.sku)issues.push("Missing stable SKU.");if(!item.title||item.title.length>80)issues.push("Title must contain 1-80 characters.");if(!item.description)issues.push("Description is missing.");if(!item.categoryId||item.leafCategory!==true)issues.push("A confirmed leaf category is required.");if(!item.condition)issues.push("Condition is missing.");if(!(item.photos||[]).length)issues.push("At least one ordered photo is required.");if((item.photos||[]).some(x=>!x.sha256))issues.push("Every photo requires a source digest.");if(!Number.isFinite(Number(item.price))||Number(item.price)<=0||item.priceApproved!==true)issues.push("An approved item-specific price is required.");if(!item.packageDetails?.weight||!item.packageDetails?.dimensions)issues.push("Package weight and dimensions are required.");for(const key of ["paymentPolicyId","fulfillmentPolicyId","returnPolicyId"])if(!item.policies?.[key])issues.push(`Missing ${key}.`);if(!item.merchantLocationKey)issues.push("Inventory location is missing.");if((item.unresolvedClaims||[]).length)issues.push("Unresolved factual claims remain.");return{ready:issues.length===0,issues}}
export function compareManifest(manifest,remote){const normalized=buildManifest({...remote,itemId:manifest.itemId,sku:manifest.sku}).manifest,diffs=[];for(const key of ["sku","photos","title","description","categoryId","condition","aspects","price","quantity","bestOfferEnabled","packageDetails","policies","merchantLocationKey"])if(stableJson(manifest[key])!==stableJson(normalized[key]))diffs.push(key);return{pass:diffs.length===0,diffs,actualHash:hash(normalized),expectedHash:hash(manifest)}}
export function recoverUnknown({sku,offers=[],listings=[]}){const result=classifyRemote({sku,inventoryOffers:offers,sellerListings:listings});if(result.classification==="ALREADY_LIVE"&&result.offers.length<=1)return{action:"RECONCILE_LIVE",result};if(result.classification==="RECOVERABLE")return{action:"RECOVER_OFFER",result};if(result.classification==="CLEAR")return{action:"RETRY_ONCE",result};return{action:"BLOCK",result}}
