import {env} from "cloudflare:workers";
import {getD1} from "../db";
import {viewerEmail} from "./ebay";

export function requireOwner(request:Request){const email=viewerEmail(request);if(!email)throw new Error("Sign in to Live Wire Listing Studio first.");return email}
export function stableJson(value:any):string{if(value===null||typeof value!=="object")return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(stableJson).join(",")}]`;return`{${Object.keys(value).sort().map(k=>`${JSON.stringify(k)}:${stableJson(value[k])}`).join(",")}}`}
export async function sha256(value:string|ArrayBuffer){const bytes=typeof value==="string"?new TextEncoder().encode(value):value;return[...new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))].map(x=>x.toString(16).padStart(2,"0")).join("")}
export async function beginOperation(input:{request:Request;itemId?:string;batchId?:string;type:string;environment:string;intent:any;identity:string}){const owner=requireOwner(input.request),db=getD1(),requestJson=stableJson(input.intent),requestHash=await sha256(requestJson),idempotencyKey=await sha256(`${owner}|${input.environment}|${input.type}|${input.identity}|${requestHash}`),now=Date.now();const existing=await db.prepare("SELECT * FROM studio_operations WHERE owner_email=? AND idempotency_key=? ORDER BY attempt DESC LIMIT 1").bind(owner,idempotencyKey).first<any>();if(existing?.status==="succeeded")return{operation:existing,replay:true};if(existing?.status==="running"||existing?.status==="ambiguous")return{operation:existing,reconcile:true};const attempt=Number(existing?.attempt||0)+1,id=crypto.randomUUID();await db.prepare("INSERT OR IGNORE INTO studio_operations (id,owner_email,item_id,batch_id,idempotency_key,operation_type,environment,request_hash,request_json,attempt,status,started_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,owner,input.itemId||null,input.batchId||null,idempotencyKey,input.type,input.environment,requestHash,requestJson,attempt,"running",now).run();const claimed=await db.prepare("SELECT * FROM studio_operations WHERE owner_email=? AND idempotency_key=? AND attempt=?").bind(owner,idempotencyKey,attempt).first<any>();if(!claimed)throw new Error("Unable to claim the durable operation.");if(claimed.id!==id)return{operation:claimed,reconcile:claimed.status==="running"||claimed.status==="ambiguous",replay:claimed.status==="succeeded"};return{operation:claimed,replay:false}}
export async function finishOperation(id:string,status:"succeeded"|"failed"|"ambiguous",result?:any,error?:any){await getD1().prepare("UPDATE studio_operations SET status=?, remote_result_json=?, error_json=?, finished_at=? WHERE id=?").bind(status,result===undefined?null:stableJson(result),error===undefined?null:stableJson(error),Date.now(),id).run()}
export async function putImage(owner:string,itemId:string,photo:{id:string;fileName:string;contentType:string;ordinal:number;data:ArrayBuffer}){const bucket=(env as any).IMAGES;if(!bucket)throw new Error("Durable image storage is unavailable.");const digest=await sha256(photo.data),key=`${owner}/${itemId}/${digest}`;await bucket.put(key,photo.data,{httpMetadata:{contentType:photo.contentType}});await getD1().prepare("INSERT INTO studio_photos (id,item_id,object_key,sha256,content_type,file_name,ordinal,created_at) VALUES (?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET object_key=excluded.object_key,sha256=excluded.sha256,content_type=excluded.content_type,file_name=excluded.file_name,ordinal=excluded.ordinal").bind(photo.id,itemId,key,digest,photo.contentType,photo.fileName,photo.ordinal,Date.now()).run();return{...photo,objectKey:key,sha256:digest,data:undefined}}
