export type ContentStatus="incomplete"|"generated"|"reviewed"|"approved";
export type EvidenceStatus="confirmed"|"uncertain"|"contradicted";
export type EbaySyncStatus="absent"|"synchronized"|"locally_changed"|"remotely_changed";
export type OfferStatus="absent"|"draft"|"invalid"|"publishable";
export type PublicationStatus="unpublished"|"publishing"|"live"|"ended";
export type OperationStatus="idle"|"running"|"failed"|"retrying";
export type EbayEnvironment="sandbox"|"production";
export type WorkflowDimensions={content:ContentStatus;evidence:EvidenceStatus;sync:EbaySyncStatus;offer:OfferStatus;publication:PublicationStatus;operation:OperationStatus;environment:EbayEnvironment;pendingRevision?:boolean};
export function workflowLabel(s:WorkflowDimensions){if(s.publication==="live")return s.pendingRevision&&s.operation==="failed"?"Live - revision failed":"Live";if(s.publication==="ended")return"Ended";if(s.publication==="publishing")return"Publishing";if(s.operation==="retrying")return"Retrying";if(s.operation==="failed")return"Needs retry";if(s.evidence==="contradicted")return"Evidence conflict";if(s.evidence==="uncertain"||s.content==="reviewed")return"Needs review";if(s.offer==="publishable")return"Ready to publish";if(s.offer==="invalid")return"Offer blocked";if(s.offer==="draft")return"Unpublished offer";if(s.content==="approved")return"Ready for eBay";if(s.content==="generated")return"Copy generated";return"Preparing"}
export type PublicationReadiness={environment:EbayEnvironment;hasDurableImages:boolean;titleValid:boolean;guideValid:boolean;leafCategory:boolean;conditionAllowed:boolean;identifiersValid:boolean;requiredAspectsValid:boolean;quantityValid:boolean;formatValid:boolean;packageValid:boolean;bestOfferConfigured:boolean;policiesValid:boolean;locationValid:boolean;priceApproved:boolean;evidenceResolved:boolean};
export function publicationBlockers(i:PublicationReadiness){const checks:[keyof PublicationReadiness,string][]=[["hasDurableImages","Store every photograph durably."],["titleValid","Fix the eBay title."],["guideValid","Fix listing-guide violations."],["leafCategory","Choose a leaf category."],["conditionAllowed","Choose an allowed condition."],["identifiersValid","Supply required product identifiers or a valid exemption."],["requiredAspectsValid","Supply required item specifics."],["quantityValid","Set a valid quantity."],["formatValid","Choose a supported listing format."],["packageValid","Supply package weight and dimensions."],["bestOfferConfigured","Confirm Best Offer settings."],["policiesValid","Select valid payment, fulfillment, and return policies."],["locationValid","Select an enabled inventory location."],["priceApproved","Approve the proposed price."],["evidenceResolved","Resolve uncertain or contradicted listing facts."]];const out=checks.filter(([k])=>!i[k]).map(([,m])=>m);if(i.environment!=="production")out.unshift("Switch to the Production environment.");return out}
